### ISSUE TITLE
Prepare/Release version 1.0.0 of org.kiwix.libkiwix

### ISSUE THREAD

**Issue by kelson42** [kiwix/java-libkiwix#42]
- [x] Secure the CI is green on git `main`
- [x] Update the Changelog
- [x] Check if this new release use latest version of libkiwix and libzim
- [x] Update version
- [x] Close current milestone and create new one incrementaly (_a priori_ a minor version)
- [x] Create a tag on git
- [x] Secure new version is published on Maven Central
- [x] Update the Github release with the Changelog
- [ ] Create new empty entry in Changelog (placeholder for future entries)
- [ ] Advertise this new version

**Comment by kelson42** [comment]
@MohitMaliDeveloper @mgautierfr Why you just have release version 11 and not version 12?!

**Comment by kelson42** [comment]
I see that someone has uploaded binaries to https://search.maven.org/artifact/org.kiwix.libkiwix/libkiwix. Who has done this and how?

**Comment by kelson42** [comment]
@MohitMaliDeveloper @mgautierfr ?

**Comment by mgautierfr** [comment]
> I see that someone has uploaded binaries to https://search.maven.org/artifact/org.kiwix.libkiwix/libkiwix. Who has done this and how?

It is not me.

> I wonder as well if it should not be better org.kiwix/libkiwix instead of org.kiwix.libkiwix/libkiwix?

Yes, I think so.

**Comment by kelson42** [comment]
@MohitMaliDeveloper I need your feedback here

**Comment by MohitMaliFtechiz** [comment]
> I see that someone has uploaded binaries to https://search.maven.org/artifact/org.kiwix.libkiwix/libkiwix. Who has done this and how?

I accidentally uploaded the artifact while testing the download of the staging artifact. This was a mistake since the release and drop options are positioned closely together and quite small. The release was not intentional.

> I wonder as well if it should not be better org.kiwix/libkiwix instead of org.kiwix.libkiwix/libkiwix?

I believe that's a valid consideration since `org.kiwix` is the group id and `libkiwix` is the artifact id. It is good to use `org.kiwix/libkiwix`. We have released `1.0.0` for `org.kiwix.libkiwix/libkiwix` if we use `org.kiwix/libkiwix` then we can upload this new artifact with version `1.0.0`.

**Comment by kelson42** [comment]
@MohitMaliFtechiz Don't forget all the checkboxes in the ticket description!

**Comment by kelson42** [comment]
@MohitMaliFtechiz published... but still not visible on MavenCentral... I guess it takes a few hours?!

**Comment by MohitMaliFtechiz** [comment]
> @MohitMaliFtechiz published... but still not visible on MavenCentral... I guess it takes a few hours?!

@kelson42 Now it is live on Maven https://mvnrepository.com/artifact/org.kiwix/libkiwix/1.0.0
